### ISSUE TITLE
Use acorn & astring in transpiler

### ISSUE THREAD

**Issue by 0918nobita** [LingDong-/psvg#18]
The current transpiler manipulates JS source code in string form, which makes it quite difficult to understand the behavior of generated JS program and to make changes.
In order to simplify the logic of transpiler, I think we should manipulate ESTree-compliant objects and finally convert them to source code in string form.

As a library to generate JS source code from ESTree-compliant objects, I suggest [astring](https://github.com/davidbonnet/astring) package.
It works very fast, so there seems to be no need to worry about changes in performance.

Also, to parse the attribute values of PSVG elements to ESTree-compliant object, JavaScript parser such as [acorn](https://github.com/acornjs/acorn) is needed.

TypeScript type definitions for ESTree-compliant objects is provided via `@types/estree` package.

Example of JS code generation:

```typescript
import type {
  Program,
  ExpressionStatement,
  CallExpression,
  MemberExpression,
  Identifier,
  Literal,
} from 'estree';
import { generate } from 'astring';

const consoleIdent: Identifier = {
  type: 'Identifier',
  name: 'console',
};

const logIdent: Identifier = {
  type: 'Identifier',
  name: 'log',
};

const memberExpr: MemberExpression = {
  type: 'MemberExpression',
  object: consoleIdent,
  property: logIdent,
  computed: false,
  optional: false,
};

const strLit: Literal = {
  type: 'Literal',
  value: 'Hello, world!',
};

const callExpr: CallExpression = {
  type: 'CallExpression',
  callee: memberExpr,
  arguments: [strLit],
  optional: false,
};

const exprStmt: ExpressionStatement = {
  type: 'ExpressionStatement',
  expression: callExpr,
};

const program: Program = {
  type: 'Program',
  sourceType: 'module',
  body: [exprStmt],
};

console.log(generate(program)); // => console.log("Hello, world!");
```

**Comment by LingDong-** [comment]
Hi @0918nobita,

Thanks a lot for the detailed proposal! I thought about this carefully, and came up with my list of pros and cons. Overall I think I'm inclined to move forward with the proposal!

Cons:
- introduces 2 dependencies (whereas 0 before)
- library size will increase about six-fold
- introduces complexity and overhead (probably very small as you said)
- one idea I was having is to write a full interpreter instead of the current transpiler to JS (which of course also has pros and cons). The other idea is to keep improving the transpiler we have now. If we decide to add acorn/astring it seems like we'll commit to the latter approach from now on. So it's an important decision to make.

Pros:
- catch user syntax errors in advance
- easier to implement "cleansing" of the code in XML attributes. I think eventually user should not be able to execute arbitrary JavaScript in the attributes like now (or, it needs to explicitly permitted with a compiler option). I think we should only allow (1) arithmetic/logical operators, and (2) function call. (This keeps the PSVG spec simple, and makes it easy for other people to make implementations (interpreters as well as transpilers) in other languages/environments.) By using acorn I think we can simply walk the AST to catch all the JS syntax not allowed by PSVG, emitting warnings/errors.
- this is a small thing, but we'll get "prettified" intermediate JS code for free (instead of the garbled garbage we have now :)

Overall I think the benefits overweighs the cons. Curious to know what y'all think about this list @0918nobita @antfu .

Just to make sure (sorry as I'm not familiar with this), for the browser build, our workflow will automatically concatenate the source code of acorn and astring to our own, so user still only needs to include one script, that right?

So please feel free to open a pull request! (and thanks again for all the contributions!)

**Comment by 0918nobita** [comment]
As @LingDong- said, this proposal is based on the assumption that we will proceed with the current transpiler refactoring.

To be honest, I think implementing a full interpreter instead of improving the transpiler will simplify the logic and make it easier to debug, add features, and tune performance. For this choice, it will be necessary to create a separate Issue and carefully sort out the pros and cons while building prototypes.

Either way, `acorn` remains useful for checking XML attribute values.

> Just to make sure (sorry as I'm not familiar with this), for the browser build, our workflow will automatically concatenate the source code of acorn and astring to our own, so user still only needs to include one script, that right?

We will need to fix the current build configuration.
Since `tsup` is designed for Node.js libraries (internally, it calls `esbuild` with `--platform=node` option), they will not be bundled, leaving `require("acorn")` / `require("astring")` in the output code.
To bundle all dependencies, we will need to stop using `tsup` and use `esbuild` directly with `--platform=browser` option.

**Comment by LingDong-** [comment]
@0918nobita , Thanks!

> For this choice, it will be necessary to create a separate Issue and carefully sort out the pros and cons while building prototypes.

I opened a new issue #19, let's bring the discussion about that there!

> Either way, acorn remains useful for checking XML attribute values.

But if we're writing our own interpreter, wouldn't we be parsing those attributes ourselves? Or do you envision using acorn as part of that interpreter? I'm more inclined to go full "DIY" if we decide to write an interpreter from scratch though. Since acorn is a JS parser, wouldn't it be either "overkill" if we stay as a subset of JS, or "limiting" if the PSVG ever need features outside of JS syntax in the future?

**Comment by 0918nobita** [comment]
> But if we're writing our own interpreter, wouldn't we be parsing those attributes ourselves? Or do you envision using acorn as part of that interpreter? I'm more inclined to go full "DIY" if we decide to write an interpreter from scratch though. Since acorn is a JS parser, wouldn't it be either "overkill" if we stay as a subset of JS, or "limiting" if the PSVG ever need features outside of JS syntax in the future?

I was thinking of using `acorn` as part of the interpreter, but it is true that the method is overkill and may be obstacle to extend the language feature. As you say, if we really implement the interpreter, it looks better to implement it completely by ourselves :)
